version: "2"
services:
  web: 
    build: .
    ports: 
      - "80:80"
    volumes: 
      - ./my-httpd.conf:/usr/local/apache2/conf/httpd.conf
      #- local path to source code tree
    depends_on:
      - "db"

  db:
    image: postgres:latest
    volumes: 
      - postgres-config:/etc/postgresql
      - postgres-data:/var/lib/postgresql/data
      - postgres-logs:/var/log/postgresql
      - ./database-backup:/database-backup

volumes:
  postgres-config:
  postgres-data:
  postgres-logs:
    